name: typo3-mcp-server-content-planner
type: php
docroot: .Build
php_version: "8.2"
webserver_type: apache-fpm
xdebug_enabled: false
additional_fqdns: []
database:
    type: mariadb
    version: "10.6"
hooks:
    post-start:
        - exec: composer install --ignore-platform-reqs --no-scripts
webimage_extra_packages: [libxml2-utils, php8.2-pcov]
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
